# -*- coding: utf-8 -*-
"""bake_colored_breps.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITndIGRoKkkwUYWOSWEvP2TFKH5Ny8zd
"""

import scriptcontext as sc
import Rhino
import System.Drawing as sd

if bake and breps and colors:

    sc.doc = Rhino.RhinoDoc.ActiveDoc

    for i in range(len(breps)):
        brep = breps[i]
        color = colors[i]


        if isinstance(color, list) and len(color) == 3:
            color = sd.Color.FromArgb(int(color[0]), int(color[1]), int(color[2]))
        elif hasattr(color, 'ToArgbColor'):
            color = color.ToArgbColor()
        elif isinstance(color, sd.Color):
            pass
        else:
            continue
        mat = Rhino.DocObjects.Material()
        mat.DiffuseColor = color
        mat.Name = "BrepColor_" + str(i)
        mat_index = sc.doc.Materials.Add(mat)

        attr = Rhino.DocObjects.ObjectAttributes()
        attr.MaterialIndex = mat_index
        attr.MaterialSource = Rhino.DocObjects.ObjectMaterialSource.MaterialFromObject


        sc.doc.Objects.AddBrep(brep, attr)

    sc.doc.Views.Redraw()
    sc.doc = ghdoc