# -*- coding: utf-8 -*-
"""vector_field_arrows_Line.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITndIGRoKkkwUYWOSWEvP2TFKH5Ny8zd
"""

import Rhino.Geometry as rg
import System.Drawing as sd
import math

lines = []
arrowheads = []

for i in range(len(P)):
    pt = P[i]
    vec = V[i]
    length = vec.Length



    end_pt = pt + vec
    line = rg.Line(pt, end_pt)
    lines.append(line)


    # Normalize vector to get direction
    dir_vec = rg.Vector3d(vec)
    dir_vec.Unitize()

    # Scale vector for arrow size
    arrow_len = vec.Length * 0.1
    base_pt = end_pt - dir_vec * arrow_len


    side_angle = math.radians(20)
    rot1 = rg.Transform.Rotation(side_angle, rg.Vector3d.ZAxis, end_pt)
    rot2 = rg.Transform.Rotation(-side_angle, rg.Vector3d.ZAxis, end_pt)

    side1 = rg.Point3d(base_pt)
    side2 = rg.Point3d(base_pt)

    side1.Transform(rot1)
    side2.Transform(rot2)

    triangle = rg.Polyline([side1, end_pt, side2, side1])
    arrowheads.append(triangle)