# -*- coding: utf-8 -*-
"""Vector_Arrow_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ITndIGRoKkkwUYWOSWEvP2TFKH5Ny8zd
"""

import Rhino.Geometry as rg

final_cyl = []
final_cone = []


for i in range(len(P)):
    pt = P[i]
    vec = V[i]

    if vec.IsZero: continue

    length = vec.Length
    if length <= cone_height:
        continue

    dir_vec = rg.Vector3d(vec)
    dir_vec.Unitize()

    end_pt = pt + vec
    base_pt = pt + dir_vec * (length - cone_height)


    cyl_plane = rg.Plane(pt, dir_vec)
    cyl_circle = rg.Circle(cyl_plane, radius)
    cylinder = rg.Cylinder(cyl_circle, length - cone_height)
    cyl_brep = cylinder.ToBrep(True, True)


    cone_plane = rg.Plane(base_pt, dir_vec)
    cone = rg.Cone(cone_plane, cone_height, cone_radius)
    cone_brep = cone.ToBrep(True)



    final_cyl.append(cyl_brep)
    final_cone.append(cone_brep)